In [1]:
##### This code is from Updated Testing Reddit - No Con- bias (Fictitious Play)-01092022
##### This code replace the big real datanetwork with small sythetic network 
import scipy
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from itertools import combinations
import time
import random
from scipy.stats import beta
import pandas as pd
import copy
%matplotlib inline
#%run pure_strategy_selection.ipynb  #include simple selection algorithm
import scipy.io
import collections
import sys


## Mathmatic Functions

In [3]:
# centers the opinion vector around 0\n",
def mean_center(op, n):
    ones = np.ones((n, 1))
    x = op - (np.dot(np.transpose(op),ones)/n) * ones
    return x
    
# compute number of edges, m\n
def num_edges(L, n):
    m = 0
    for i in range(n):
        for j in range(n):
            if i > j and L[i,j] < 0:
                m += 1            
    return m

# maximizing polarization only: \\bar{z}^T \\bar{z}   
def obj_polarization(A, L, op, n):
    op_mean = mean_center(op, n)
    z_mean = np.dot(A, op_mean) 
    return np.dot(np.transpose(z_mean), z_mean)[0,0] 

def obj_polarization_1(A, L, op, n):
    z = np.dot(A, op) 
    z_mean = mean_center(z, n)
    return np.dot(np.transpose(z_mean), z_mean)[0,0] 

# Calculate innate polarization
def obj_innate_polarization(s, n):  
#     np.set_printoptions(precision=5)
    op_mean = mean_center(s, n)
    return np.dot(np.transpose(op_mean), op_mean)[0,0]

In [4]:
# Parameters for the network

np.set_printoptions(precision=5)

## Creating Network
### 1. Make Random Network

In [6]:
# name = "Karate"
# filename = "%s.ipynb" % name
# print(filename)
# %run filename
#%run sync_net4.ipynb
#%run Karate.ipynb
#%run Twitter.ipynb
#%run Reddit.ipynb
n=20
%run Synthetic.ipynb

### Min [245, ] [284, ]       Max [50, ] [481, ] 

### 4. Equilibrium & Polarization  - based on derivation
$$P(z) = z ^T * z $$


In [13]:

## s =  make_innat_opinions(n, c1)
# print('Innate Opinion')
# print(s)
# print('Equilibrium Opinion')
# print(np.dot(A, s))

op = s
y = mean_center(s,n)
# print(y)
innat_pol = np.dot(np.transpose(y), y)[0,0] 
print('Innate_polarization:')
print(innat_pol)

# Test equilibrium polarization
equ_pol = obj_polarization(A, L, s, n)
print('Equi_polarization:')
print(equ_pol)

di = equ_pol-innat_pol
print("Difference:")
print(di)

NameError: name 's' is not defined

In [ ]:
payoff_matrix = [np.empty((0, 2*n), float)]

# 5. Innate Op and Game

In [17]:
def make_payoff_row(op1,v2, A, L, n):
    payoff_row = np.zeros(2*n)

    for column in range(2*n):
#         print(column)
        v1 = int(column/2)  #i.e., column 11 is agent 5, opinion 1
        max_opinion = column%2
#         print(v1, max_opinion)
        # update the maximizer's change to the opinion array that has changed by minimizer(op1)
        op2 = copy.copy(op1)
        op2[v1,0] = max_opinion
        # calculate the polarization with both max and min's action
        payoff_row[column] = obj_polarization(A, L, op2, n)
    
    j_1 = 2*v2 + 0
    j_2 = 2*v2 + 1
    O_P = obj_polarization(A, L, s, n)
    payoff_row[j_1] = O_P
    payoff_row[j_2] = O_P
    
    return payoff_row

def make_payoff_matrix(s,n, A, L):
    payoff_matrix = np.empty((0, 2*n), float)
    C1 = list(range(n))    # for all agent 
    for v2 in C1:         
            #print('Minimizer start from agent'+str(v2))
            min_opi_option = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0] #Min has two options to change agent v2's opinion
            for min_op in min_opi_option:
                     op = copy.copy(s)
                     op[v2] = min_op
                     payoff_row = make_payoff_row(op,v2, A, L, n) 
#                      print(payoff_row)
                     payoff_matrix = np.vstack([payoff_matrix, payoff_row])
    return payoff_matrix

## 5A. Payoff Matrix - op dynamic

In [42]:
n=20
for i in range(1):
    s,A,L = make_sync_network(n)
    payoff_matrix = make_payoff_matrix(s,n, A,L)
    pd.DataFrame(payoff_matrix).to_csv('Generated networks/Sythetic Payoff Matrix_'+str(i)+'.csv')
#pd.DataFrame(payoff_matrix).to_csv('Karate Discrete Payoff Matrix.csv')
# pd.DataFrame(payoff_matrix).to_csv('Reddit Discrete Payoff Matrix1.csv')
#pd.DataFrame(payoff_matrix).to_csv('Twitter Discrete Payoff Matrix1.csv')



Minimizer start from agent0
Minimizer start from agent1
Minimizer start from agent2
Minimizer start from agent3
Minimizer start from agent4
Minimizer start from agent5
Minimizer start from agent6
Minimizer start from agent7
Minimizer start from agent8
Minimizer start from agent9
Minimizer start from agent10
Minimizer start from agent11
Minimizer start from agent12
Minimizer start from agent13
Minimizer start from agent14
Minimizer start from agent15
Minimizer start from agent16
Minimizer start from agent17
Minimizer start from agent18
Minimizer start from agent19
Minimizer start from agent0
Minimizer start from agent1
Minimizer start from agent2
Minimizer start from agent3
Minimizer start from agent4
Minimizer start from agent5
Minimizer start from agent6
Minimizer start from agent7
Minimizer start from agent8
Minimizer start from agent9
Minimizer start from agent10
Minimizer start from agent11
Minimizer start from agent12
Minimizer start from agent13
Minimizer start from agent14
Minim

In [20]:
import pandas as pd

# Properly formatted file path for Windows
file_path = r'C:\Users\xz47\OneDrive\Misinfo Paper\One Node - Final\12092023_PoGame\12092023_PoGame\Karate Discrete Payoff Matrix.csv'
#r'C:\Users\xz47\OneDrive\Misinfo Paper\One Node - Final\12092023_PoGame\12092023_PoGame\Karate NoOpDyn Discrete Payoff Matrix1.csv'
#r'C:\Users\xz47\OneDrive\Misinfo Paper\One Node - Final\12092023_PoGame\12092023_PoGame\Karate NoOpDyn Discrete Payoff Matrix1.csv'

# Import data
df = pd.read_csv(file_path,header=None)
matrix = df.to_numpy()
print(matrix.shape)

# Continue with your analysis...


(374, 68)


In [22]:
print(matrix)
print(matrix[0][0])
# Zero-sum Game
p0 = matrix[0][0]

change = matrix - p0
print(change)

[[0.16  0.16  0.133 ... 0.12  0.16  0.11 ]
 [0.16  0.16  0.137 ... 0.124 0.165 0.114]
 [0.16  0.16  0.141 ... 0.128 0.17  0.118]
 ...
 [0.118 0.169 0.122 ... 0.111 0.16  0.16 ]
 [0.114 0.163 0.118 ... 0.107 0.16  0.16 ]
 [0.11  0.158 0.114 ... 0.104 0.16  0.16 ]]
0.159675269
[[ 0.000e+00  0.000e+00 -2.638e-02 ... -3.955e-02  6.092e-05 -4.978e-02]
 [ 0.000e+00  0.000e+00 -2.268e-02 ... -3.567e-02  5.236e-03 -4.608e-02]
 [ 0.000e+00  0.000e+00 -1.874e-02 ... -3.154e-02  1.065e-02 -4.214e-02]
 ...
 [-4.155e-02  9.074e-03 -3.735e-02 ... -4.842e-02  0.000e+00  0.000e+00]
 [-4.577e-02  3.377e-03 -4.145e-02 ... -5.223e-02  0.000e+00  0.000e+00]
 [-4.978e-02 -2.102e-03 -4.534e-02 ... -5.582e-02  0.000e+00  0.000e+00]]


In [26]:
import nashpy as nash
import numpy as np
###################################### Zero-sum Game
p0 = matrix[0][0]
# Calculate the change in polarization
delta_polarization =  matrix - p0
# print(delta_polarization)

# Define payoff matrices for both players
payoff_matrix_1 = matrix - p0
payoff_matrix_2 = p0- matrix 
# print(payoff_matrix_1)
# print(payoff_matrix_2)

####################################### Non-zero-sum
# Replace 0 with -10000
payoff_matrix_1[payoff_matrix_1 == 0] = -10000
payoff_matrix_2[payoff_matrix_2 == 0] = -10000
# print(payoff_matrix_2)
# # Create the game
game = nash.Game(payoff_matrix_1, payoff_matrix_2)

# Find Nash Equilibrium using the Lemke-Howson algorithm
equilibrium = game.lemke_howson(initial_dropped_label=1)
print("Nash Equilibrium:", equilibrium)

Nash Equilibrium: (array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
 

In [309]:
print(len(equilibrium[0]))

374


In [30]:

# Identify significant strategies for maximizer
for i in range(0, len(equilibrium[0])):  # Step through each agent's actions
    agent_index = i // 11
    action_0_prob = equilibrium[0][i]
    chosen_action = i%11
    # action_1_prob = equilibrium[0][i+1]
    if action_0_prob>0:
        print(f"Maximizer Agent {agent_index} chooses Action {chosen_action} with probability {action_0_prob}")
print('=================================================')
# Identify significant strategies for minimizer
for i in range(0, len(equilibrium[1])):  # Step through each agent's actions
    agent_index = i // 2
    action_probabilities = equilibrium[1][i]
    chosen_action = i%2
    if action_probabilities>0:
        print(f"Minimizer Agent {agent_index} chooses Action {chosen_action} with probability {action_probabilities}")


Maximizer Agent 11 chooses Action 10 with probability 0.770563727603345
Maximizer Agent 16 chooses Action 10 with probability 0.22943627239665493
Minimizer Agent 6 chooses Action 0 with probability 0.784011484864908
Minimizer Agent 29 chooses Action 1 with probability 0.21598851513509207


In [303]:
# # # Find Nash Equilibrium using the Lemke-Howson algorithm
# # equilibrium = game.lemke_howson(initial_dropped_label=0)
# # print("Nash Equilibrium:", equilibrium)

# # Find non-zero indices for Player 1
# non_zero_indices_1 = np.nonzero(equilibrium[0])[0]
# # Find non-zero indices for Player 2
# non_zero_indices_2 = np.nonzero(equilibrium[1])[0]

# # Print the indices and corresponding probabilities for each player
# print("Player 1 Non-Zero Strategy Indices and Probabilities:")
# for index in non_zero_indices_1:
#     print(f"Strategy {index}: Probability {equilibrium[0][index]}")

# print("\nPlayer 2 Non-Zero Strategy Indices and Probabilities:")
# for index in non_zero_indices_2:
#     print(f"Strategy {index}: Probability {equilibrium[1][index]}")

Player 1 Non-Zero Strategy Indices and Probabilities:
Strategy 131: Probability 0.770563727603345
Strategy 186: Probability 0.22943627239665493

Player 2 Non-Zero Strategy Indices and Probabilities:
Strategy 12: Probability 0.784011484864908
Strategy 59: Probability 0.21598851513509207


In [11]:
### Save simulation result to TXT file

# with open('Result'+str(Network)+'.'+str(Experiment)+'.txt', "a") as f:
# #     print(Experiment_note, file=f)
#     print('Initial Condition -(agent, opinion, pol)', file=f)
#     print('Innate op'+str(s),file=f)
#     print('Adjacency matrix'+ str(G), file=f)
# np.arange(0,1.01,0.01)

## 5B. Payoff Matrix - No Op Dynamic 

In [1]:
def make_payoff_row_noopdy(op1,v2, A, L, n):
    payoff_row = np.zeros(2*n)

    for column in range(2*n):
#         print(column)
        v1 = int(column/2)  #i.e., column 11 is agent 5, opinion 1
        max_opinion = column%2
#         print(v1, max_opinion)
        # update the maximizer's change to the opinion array that has changed by minimizer(op1)
        op2 = copy.copy(op1)
        op2[v1,0] = max_opinion
        # calculate the polarization with both max and min's action
        payoff_row[column] = obj_innate_polarization(op2, n) 
    
    j_1 = 2*v2 + 0
    j_2 = 2*v2 + 1
    O_P = obj_innate_polarization(s, n)
    payoff_row[j_1] = O_P
    payoff_row[j_2] = O_P
    
    return payoff_row

def make_payoff_matrix_noopdy(s,n):
    payoff_matrix = np.empty((0, 2*n), float)
    C1 = list(range(n))    # for all agent 
    for v2 in C1:         
            print('Minimizer start from agent'+str(v2))
            min_opi_option = np.arange(0,1.01,0.01) #Min has two options to change agent v2's opinion
            for min_op in min_opi_option:
                     op = copy.copy(s)
                     op[v2] = min_op
                     payoff_row = make_payoff_row_noopdy(op,v2, A, L, n) 
#                      print(payoff_row)
                     payoff_matrix = np.vstack([payoff_matrix, payoff_row])
    return payoff_matrix

In [10]:
payoff_matrix = make_payoff_matrix_noopdy(s,n)
pd.DataFrame(payoff_matrix).to_csv('Karate NoOpDyn Discrete Payoff Matrix1.csv')
#pd.DataFrame(payoff_matrix).to_csv('Reddit NoOpDyn Discrete Payoff Matrix1.csv')
#pd.DataFrame(payoff_matrix).to_csv('Twitter NoOpDyn Discrete Payoff Matrix1.csv')

