In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import numpy as np

# Create dataset
y = np.array([[0, 1, 1, 0],[0, 1, 1, 0]])  # Target

# Create graphs
graph1 = {'adj': np.array([[0, 1, 1, 0],
                           [1, 0, 0, 0],
                           [1, 0, 0, 1],
                           [0, 0, 1, 0]]),
          'features': np.array([[1],
                                 [3],
                                 [5],
                                 [7]])}

graph2 = {'adj': np.array([[0, 1, 0, 0],
                           [1, 0, 1, 1],
                           [0, 1, 0, 1],
                           [0, 1, 1, 0]]),
          'features': np.array([[9],
                                 [11],
                                 [13],
                                 [15]])}

graphs = [graph1, graph2]


In [35]:
# Concatenate features and adjacency matrices for each graph
X_graphs = []
for graph in graphs:
    X_graph = np.concatenate([graph['adj'], graph['features']], axis=1)
    X_graphs = np.concatenate([X_graphs, X_graph], axis=0)
print('X_graphs, y')
print(X_graphs)
# Train random forest tree
rfc = RandomForestClassifier(n_estimators=4)
rfc.fit(X_graphs, y)

# Predict on test data
graph_test = {'adj': np.array([[0, 1, 0, 0],
                               [1, 0, 0, 1],
                               [0, 0, 0, 1],
                               [0, 1, 1, 0]]),
              'features': np.array([[17],
                                     [19],
                                     [21],
                                     [23]])}

X_test = np.concatenate([graph_test['adj'], graph_test['features']], axis=1)
y_pred = rfc.predict(X_test)

# Calculate accuracy
y_true = np.array([0, 1, 0, 1])
accuracy = accuracy_score(y_true, y_pred)
print('Accuracy:', accuracy)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
%run excute-nonZS-MaxMin.ipynb

adj_list = []
features_list = []
labels_list = []
for i in range(10):
    (v1,v2, max_opinion, min_opinion,max_pol, s, G, a,b,c,d) = run(n)
    adj_list.append(torch.tensor(G))
    features_list.append(torch.tensor(s))
    #create min_action label
    c1 = [0 for i in range(20)]
    c1[v2]=1
    print(c1)
    labels= c1
    labels_list.append(torch.tensor(labels))
    

# Merge adjacency matrices and node features into a single tensor
adj = torch.stack(adj_list, dim=0)  # shape: (n, num_nodes, num_nodes)
feat = torch.stack(features_list, dim=0)  # shape: (n, num_nodes, num_features)
y = torch.stack(labels_list, dim=0)  # shape: (n, num_nodes)

In [21]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier

# Generate sample data
X_graph1 = np.random.rand(10, 5)  # First graph with 10 nodes and 5 features per node
print(X_graph1)
X_graph2 = np.random.rand(10, 5)   # Second graph with 8 nodes and 5 features per node10
y = np.random.randint(2, size=(20,1))  # Binary labels for each node
print(y)
# Concatenate features for all nodes across both graphs
X_graphs = np.concatenate((X_graph1.reshape(X_graph1.shape[0], -1), 
                            X_graph2.reshape(X_graph2.shape[0], -1)))
print(X_graphs)
# Train random forest tree
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(X_graphs, y)

# Predict on test data
X_test_graph = np.random.rand(5, 5, 1)  # New graph with 5 nodes and 5 features per node
X_test = X_test_graph.reshape(X_test_graph.shape[0], -1)  # Flatten features for input
y_pred = rfc.predict(X_test)
print(y_pred)
# Calculate accuracy
y_true = np.array([0, 1, 0, 1, 1])
accuracy = accuracy_score(y_true, y_pred)
print('Accuracy:', accuracy)


[[0.01569722 0.30619455 0.49888096 0.74535952 0.1133669 ]
 [0.75801377 0.19629121 0.84513559 0.18409553 0.61194757]
 [0.36515857 0.24638383 0.74285632 0.88843585 0.85390363]
 [0.56569264 0.14911348 0.04238988 0.81810418 0.82117195]
 [0.39956381 0.49913971 0.68561303 0.08137323 0.1786056 ]
 [0.32963998 0.81131539 0.62878872 0.0785082  0.14476855]
 [0.91221068 0.24318448 0.9402355  0.03461349 0.20015443]
 [0.17865528 0.40724066 0.92795579 0.52833392 0.73364717]
 [0.54225155 0.75792774 0.78686084 0.51816104 0.71299912]
 [0.16722245 0.97424937 0.82625073 0.70197973 0.3062453 ]]
[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]]
[[0.01569722 0.30619455 0.49888096 0.74535952 0.1133669 ]
 [0.75801377 0.19629121 0.84513559 0.18409553 0.61194757]
 [0.36515857 0.24638383 0.74285632 0.88843585 0.85390363]
 [0.56569264 0.14911348 0.04238988 0.81810418 0.82117195]
 [0.39956381 0.49913971 0.68561303 0.08137323 0.1786056 ]
 [0.32963998 0.81131539 0.62

C:\Users\xzhan176\AppData\Local\Temp\ipykernel_4916\98623048.py:16: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_graphs, y)
